// <auto-generated />
using System;
using Daab.Modules.ScientistsDirectory.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Daab.Modules.ScientistsDirectory.Database.Migrations
{
    [DbContext(typeof(ScientistsContext))]
    partial class ScientistsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Daab.Modules.ScientistsDirectory.Models.FieldOfStudy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ScientistId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScientistId");

                    b.ToTable("FieldsOfStudy");
                });

            modelBuilder.Entity("Daab.Modules.ScientistsDirectory.Models.Scientist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AcademicTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Publications")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Scientists");
                });

            modelBuilder.Entity("Daab.Modules.ScientistsDirectory.Models.FieldOfStudy", b =>
                {
                    b.HasOne("Daab.Modules.ScientistsDirectory.Models.Scientist", null)
                        .WithMany("FieldsOfStudy")
                        .HasForeignKey("ScientistId");
                });

            modelBuilder.Entity("Daab.Modules.ScientistsDirectory.Models.Scientist", b =>
                {
                    b.Navigation("FieldsOfStudy");
                });
#pragma warning restore 612, 618
        }
    }
}
